---
# tasks file for install_dev_env
- name: apt | install required packages.
  become: true
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
       - unzip
       - python3
       - python3-venv

- name: Copy requirements.txt
  copy:
    src: "requirements.txt"
    dest: "/tmp"
    owner: "root"
    group: "root"
    mode: "0664"

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3

- name: Install pip requirements
  pip:
    requirements: /tmp/requirements.txt
    virtualenv: /home/vagrant/venv_automation
    virtualenv_python: python3

- name: change ownership /home/vagrant/venv_automcation folder
  ansible.builtin.file:
    path: /home/vagrant/venv_automation
    owner: vagrant
    group: vagrant
    recurse: yes
    mode: '0764'

- name: "venv | copy setenv.sh script in the HOME of the vagrant user"
  copy:
    src: "setenv.sh"
    dest: "/home/vagrant"
    owner: "vagrant"
    group: "vagrant"
    mode: "0764"

- name: Download and unarchive Packer.
  unarchive:
    src: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_{{ packer_arch }}.zip
    dest: "{{ packer_bin_path }}"
    remote_src: true
    creates: "{{ packer_bin_path }}/packer"
    mode: 0755

- name: Install taskfile from deb
  apt:
    deb: https://github.com/go-task/task/releases/download/v{{ taskfile_version }}/task_linux_amd64.deb


- name: Install docker dive tool.
  apt:
    deb: https://github.com/wagoodman/dive/releases/download/v{{ docker_dive_version }}/dive_{{ docker_dive_version }}_linux_amd64.deb
